services:
  twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
          - { name: twig.extension }
      
  twig.extension.debug:
      class: Twig_Extensions_Extension_Debug
      tags:
          - { name: twig.extension }
        
  twig.extension.intl:
      class: Twig_Extensions_Extension_Intl
      tags:
          - { name: twig.extension }
          
  twig.extension.compra:
      class: Compras\CompraBundle\Twig\Extension\CompraExtension
      tags:
          - { name: twig.extension }
          
  sonata.compras.admin.producto:
      class: Compras\CompraBundle\Admin\ProductoAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: 'Compras', label: Productos }
      arguments:
          - null
          - Compras\CompraBundle\Entity\Producto
          - CompraBundle:Admin