services:
  twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
          - { name: twig.extension }
      
  twig.extension.debug:
      class: Twig_Extensions_Extension_Debug
      tags:
          - { name: twig.extension }
        
  twig.extension.intl:
      class: Twig_Extensions_Extension_Intl
      tags:
          - { name: twig.extension }
          
  twig.extension.compra:
      class: Compras\CompraBundle\Twig\Extension\CompraExtension
      tags:
          - { name: twig.extension }