<?php

namespace Compras\CompraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function getRecentProductos($limit = 3, $offset = 0)
    {
        $q = $this->_em->createQuery(
                'SELECT t
                   FROM CompraBundle:Producto t');
        $q->setFirstResult( $offset );
        $q->setMaxResults( $limit );
     
      return $q->getResult();
    }
    
    public function getProductosByNombre($nombre)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT p
              FROM CompraBundle:Producto p
             WHERE p.nombre LIKE :nombre');
        
        $consulta->setParameter('nombre', '%'.$nombre.'%');
        
        return $consulta->getResult();
    }
    
    public function findProducto($slug)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT p
              FROM CompraBundle:Producto p
             WHERE p.slug = :slug');
        
        $consulta->setParameter('slug', $slug);
        $consulta->setMaxResults(1);
        
        return $consulta->getSingleResult();
    }
    
    public function queryTodosLosProductos()
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
            SELECT o, t FROM CompraBundle:Producto o
              JOIN o.tienda t 
          ORDER BY o.fechaPublicacion DESC');
        
        return $consulta;
    }
    
    public function findTodasLosProductos()
    {
        return $this->queryTodosLosProductos()->getResult();
    }
}
