<?php

namespace Compras\CompraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends EntityRepository
{
    public function getRecentProductos($limit = 3, $offset = 0)
    {
        $q = $this->_em->createQuery(
                'SELECT t
                   FROM CompraBundle:Producto t');
        $q->setFirstResult( $offset );
        $q->setMaxResults( $limit );
     
      return $q->getResult();
    }
}
