productos:
    pattern: /productos
    defaults: { _controller: CompraBundle:Default:listaproductos }
    
latest_productos:
    pattern:  /productos/latest/{max}
    defaults: { _controller: CompraBundle:Default:recentProductos }
