lista_productos:
    pattern: /listproductos
    defaults: { _controller: CompraBundle:Default:listaProductos }
    
latest_productos:
    pattern:  /productos/latest/{max}
    defaults: { _controller: CompraBundle:Default:recentProductosList }
    
# Ruta de la página de detalle de un producto
producto:
    pattern:  /productos/{slug}
    defaults: { _controller: CompraBundle:Default:producto }
