Cart:
    type: entity
    table: Cart
    indexes:
        IDX_AB912789DB38439E:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        itemstotal:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: itemsTotal
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            comment: ''
            column: deleted_at
        estado:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
