Tienda:
    type: entity
    table: Tienda
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        direccion:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        login:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
