Venta:
    type: entity
    table: Venta
    indexes:
        IDX_4E26C1517645698E:
            columns:
                - producto_id
        IDX_4E26C151DB38439E:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: datetime
            nullable: false
            comment: ''
    manyToOne:
        producto:
            targetEntity: Producto
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                producto_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
