<?php

namespace Compras\ShoppingCartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    public function findCartItems($usuario_id = 0)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
                SELECT  i, p
                  FROM ShoppingCartBundle:CartItem i
                  JOIN i.cart c
                  JOIN i.producto p
                 WHERE c.usuario = :usuario_id
                   AND c.estado = 1');
                
        $consulta->setParameter('usuario_id', $usuario_id);
        
        return $consulta->getResult();
    }
}
