<?php

namespace Compras\ShoppingCartBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    public function findCart($usuario_id = 0)
    {
        $em = $this->getEntityManager();
        
        $consulta = $em->createQuery('
                SELECT c, i
                  FROM ShoppingCartBundle:Cart c
                  JOIN c.items i
                 WHERE c.usuario = :usuario_id
                   AND c.estado = 1
              ORDER BY i.cantidad DESC');
        
        //$consulta->setMaxResults();
        $consulta->setParameter('usuario_id', $usuario_id);
        
        return $consulta->getResult();
    }
}
